sudo: required

language: bash

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t bpetri/buildroot_minimum_celix buildroot_minimum_celix
  - docker build -t bpetri/cagent_builder cagent_builder && docker push bpetri/cagent_builder
  - docker run bpetri/cagent_builder build_script > cagent_builder.sh && chmod +x cagent_builder.sh 

install:
  - ./cagent_builder.sh make_celix_agent

after_sucess:
  - docker push inaetics/celix_agent

